### ISSUE TITLE
Application for making custom layouts 

### ISSUE THREAD

**Issue by sajjad000** [futo-org/android-keyboard#423]
I have an idea for a separate app from futo keyboard. The idea of ​​the app is just to make custom layouts where this app has a virtual keyboard interface where you can make a specific layout from it and then when you are done the layout with the graphical interface is converted to a json or xml file and only then we send you the file on Discord and you add it to futo keyboard

**Comment by abb128** [comment]
My goal at the moment is rewriting the layout system so that creating new layouts is easy and doesn't require adding a hodgepodge of xml files. Here's a preview of how it will probably work under the new system:

```yaml
# qwerty.yaml
name: "QWERTY"
rows:
  - letters: q w e r t y u i o p
  - letters: a s d f g h j k l
  - letters: z x c v b n m
```

I'm not sure if a custom designer app would be necessary once this is complete. There will be more complex features of course, but good documentation should help
