### ISSUE TITLE
Custom Layout with Emojis Crashes Keyboard

### ISSUE THREAD

**Issue by dean-futo** [futo-org/android-keyboard#951]
### What happened?

A user reported that when they create a custom layout with multiple emojis assigned to a single long-press option, the keyboard crashes. This issue occurs when they try to access the emojis with the custom key.

### Keyboard Version

0.1.24

**Comment by unai-ndz** [comment]
I just hit this bug, seems related to the size the labels need.

e.g. This doesn't crash unless I remove the fixedColumnOrder or increase it to 4
```yaml
name: "QWERTY Reproduce bug"
rows:
  - letters:
    - ["☻", "!fixedColumnOrder!3", a23456789, b23456789, c23456789, d23456789]
    attributes: { moreKeyMode: OnlyExplicit }
  - letters: "q w e r t y u i o p"
  - letters: "a s d f g h j k l"
  - letters: z x c v b n m
```

This works
```yaml
    - ["☻", "!fixedColumnOrder!3", a234567891, b234567891, c234567891, d234567891]
```
but this crashes
```yaml
    - ["☻", "!fixedColumnOrder!3", a234567890, b23456789, c23456789, d23456789]
```

This also works
```yaml
    - ["☻", "!fixedColumnOrder!3", 1|a234567890, b23456789, c23456789, d23456789]
```

**Comment by Zvonimir-FUTO** [comment]
**Bug in Custom layout (0.1.25)**

```
Custom layout could not be loaded.

Cause: Duplicate key 'attributes'. It was previously given at line 5, column 5.

Stack trace: [com.charleskorn.kaml.YamlMap.<init>(SourceFile:96), com.charleskorn.kaml.YamlNodeReader.readNodeAndAnchor(SourceFile:326), com.charleskorn.kaml.YamlNodeReader.readNodeAndAnchor(SourceFile:168), com.charleskorn.kaml.YamlNodeReader.readNodeAndAnchor(SourceFile:469), com.charleskorn.kaml.Yaml.decodeFromString(SourceFile:177), org.futo.inputmethod.v2keyboard.LayoutManagerKt.parseKeyboardYamlString(SourceFile:14), org.futo.inputmethod.v2keyboard.KeyboardLayoutSetV2.<init>(SourceFile:232), org.futo.inputmethod.keyboard.KeyboardSwitcher.loadKeyboard(SourceFile:177), org.futo.inputmethod.latin.LatinIME.onStartInputView(SourceFile:439), android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:2897), android.inputmethodservice.InputMethodService$InputMethodImpl.restartInput(InputMethodService.java:803), android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInputWithToken(InputMethodService.java:820), android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:210), com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44), android.os.Handler.dispatchMessage(Handler.java:106), android.os.Looper.loopOnce(Looper.java:240), android.os.Looper.loop(Looper.java:351), android.app.ActivityThread.main(ActivityThread.java:8423), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)]

Layout: CustomLayout(language=en_US, layoutYaml=name: "QWERTY Reproduce bug"
rows:
  - letters:
    - ["☻", "!fixedColumnOrder!3", a23456789, b23456789, c23456789, d23456789]
    attributes: { moreKeyMode: OnlyExplicit }
    attributes: { moreKeyMode: OnlyExplicit }
  - letters: "q w e r t y u i o p"
  - letters: "a s d f g h j k l"
  - letters: z x c v b n m)
```

**Bug in LayoutManager (0.1.25)**

```
Failed to parse layout names
Message: Error while parsing layout [layouts/names.yaml], cause: Unknown property 'ipa'. Known properties are: altPages, attributes, autoShift, bottomRowHeightMode, bottomRowWidthMode, combiners, description, effectiveRows, id, languages, layoutSetOverrides, minimumBottomRowFunctionalKeyWidth, minimumFunctionalKeyWidth, name, numberRowMode, overrideWidths, rowHeightMode, rows, useZWNJKey
```
